system:
  type: "beacon"  # options: beacon, x-plane
  dt: 0.1
  use_observations: false

hjnnv:
  filtering: true
  bounding_method: "crown" # Options: crown, gt

experiment_setup:
  num_steps: 100
  expt_number: 1
  expt_type: "trajectory"
  show_plot: true
  save: false



